# Generated by Django 5.2.17 on 2026-09-25 09:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier. Safe to expose in APIs and URLs.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, help_text='Overrides the page title in search results.', max_length=70)),
                ('seo_description', models.CharField(blank=True, help_text='Meta description. Roughly 150 characters.', max_length=160)),
                ('seo_keywords', models.CharField(blank=True, max_length=255)),
                ('noindex', models.BooleanField(default=False, help_text='Ask search engines not to index this page.')),
                ('canonical_path', models.CharField(blank=True, help_text='Canonical path when this page duplicates another.', max_length=255)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'presentation page',
                'verbose_name_plural': 'presentation pages',
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
