# Generated by Django 5.2.17 on 2026-09-25 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationpage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Social sharing image. Falls back to the cover image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset'),
        ),
    ]
