# Generated by Django 5.2.17 on 2026-09-25 09:49

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier. Safe to expose in APIs and URLs.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.SmallIntegerField(help_text='0 is ground floor; negative levels are below ground.')),
                ('name', models.CharField(blank=True, help_text='Optional label, e.g. Penthouse level.', max_length=60)),
                ('unit_count', models.PositiveSmallIntegerField(default=0, help_text='Planned units on this level.')),
            ],
            options={
                'verbose_name': 'floor',
                'verbose_name_plural': 'floors',
                'ordering': ['building', 'level'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier. Safe to expose in APIs and URLs.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(help_text='Apartment number, e.g. 4B.', max_length=30)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('rented', 'Rented'), ('not_for_sale', 'Not for sale')], db_index=True, default='available', max_length=16)),
                ('usable_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('rooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('orientation', models.CharField(blank=True, help_text='North, South-West, and so on.', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Developer price. The listing price may differ.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='EUR', max_length=3)),
            ],
            options={
                'verbose_name': 'unit',
                'verbose_name_plural': 'units',
                'ordering': ['floor', 'number'],
            },
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier. Safe to expose in APIs and URLs.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Type A, 2R-60, and so on.', max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('rooms', models.PositiveSmallIntegerField(default=1)),
                ('bathrooms', models.PositiveSmallIntegerField(default=1)),
                ('usable_area', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('built_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('balcony_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'verbose_name': 'unit type',
                'verbose_name_plural': 'unit types',
                'ordering': ['development', 'rooms', 'usable_area'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier. Safe to expose in APIs and URLs.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Building A, Tower 2, and so on.', max_length=120)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('floors_above_ground', models.PositiveSmallIntegerField(default=0)),
                ('floors_below_ground', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('under_construction', 'Under construction'), ('completed', 'Completed'), ('sold_out', 'Sold out')], default='planned', max_length=24)),
                ('estimated_completion', models.DateField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('address', models.ForeignKey(blank=True, help_text='Only when the building differs from the project address.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings', to='locations.address')),
            ],
            options={
                'verbose_name': 'building',
                'verbose_name_plural': 'buildings',
                'ordering': ['development', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier. Safe to expose in APIs and URLs.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('developer_name', models.CharField(blank=True, help_text='The company building the project.', max_length=180)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('under_construction', 'Under construction'), ('completed', 'Completed'), ('sold_out', 'Sold out')], db_index=True, default='planned', max_length=24)),
                ('publication_status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('estimated_completion', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='developments', to='locations.address')),
            ],
            options={
                'verbose_name': 'development',
                'verbose_name_plural': 'developments',
                'ordering': ['-is_featured', 'name'],
            },
        ),
    ]
