# Generated by Django 5.2.17 on 2026-09-25 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developments', '0001_initial'),
        ('media', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='development',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_developments', to='media.mediaasset'),
        ),
        migrations.AddField(
            model_name='development',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_developments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='building',
            name='development',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='developments.development'),
        ),
        migrations.AddField(
            model_name='floor',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='developments.building'),
        ),
        migrations.AddField(
            model_name='floor',
            name='floor_plan',
            field=models.ForeignKey(blank=True, help_text='The floor plate drawing, stored via apps.media.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_plan_for_floors', to='media.mediaasset'),
        ),
        migrations.AddField(
            model_name='unit',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='developments.floor'),
        ),
        migrations.AddField(
            model_name='unit',
            name='listing',
            field=models.OneToOneField(blank=True, help_text='The public listing for this unit, when it should appear on the portal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit', to='properties.property'),
        ),
        migrations.AddField(
            model_name='unittype',
            name='development',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_types', to='developments.development'),
        ),
        migrations.AddField(
            model_name='unittype',
            name='layout',
            field=models.ForeignKey(blank=True, help_text='The apartment layout drawing, stored once for every unit of this type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layout_for_unit_types', to='media.mediaasset'),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='developments.unittype'),
        ),
        migrations.AddIndex(
            model_name='development',
            index=models.Index(fields=['publication_status', 'status'], name='development_publica_473b56_idx'),
        ),
        migrations.AddConstraint(
            model_name='building',
            constraint=models.UniqueConstraint(fields=('development', 'name'), name='unique_building_name_per_development'),
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(fields=('building', 'level'), name='unique_level_per_building'),
        ),
        migrations.AddConstraint(
            model_name='unittype',
            constraint=models.UniqueConstraint(fields=('development', 'code'), name='unique_unit_type_code_per_development'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['availability', 'floor'], name='development_availab_ca1a83_idx'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('floor', 'number'), name='unique_unit_per_floor'),
        ),
    ]
