# Generated by Django 5.2.17 on 2026-09-25 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier. Safe to expose in APIs and URLs.', unique=True)),
                ('action', models.CharField(db_index=True, help_text='Dotted action name owned by the emitting app, e.g. property.published.', max_length=80)),
                ('actor_label', models.CharField(blank=True, help_text='Who acted, preserved if the account is removed.', max_length=160)),
                ('target_app', models.CharField(blank=True, max_length=60)),
                ('target_model', models.CharField(blank=True, max_length=60)),
                ('target_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit event',
                'verbose_name_plural': 'audit events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_app', 'target_model', 'target_uuid', '-created_at'], name='audit_target_idx'), models.Index(fields=['actor', '-created_at'], name='audit_actor_idx')],
            },
        ),
    ]
