# Generated by Django 5.2.17 on 2026-09-25 09:49

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier. Safe to expose in APIs and URLs.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('group', models.CharField(choices=[('interior', 'Interior'), ('building', 'Building'), ('outdoor', 'Outdoor'), ('utilities', 'Utilities'), ('security', 'Security'), ('accessibility', 'Accessibility')], db_index=True, default='interior', max_length=20)),
                ('is_filterable', models.BooleanField(default=True, help_text='Appears in the public search filters.')),
                ('is_premium_filter', models.BooleanField(default=False, help_text='Filtering by this requires a subscription entitlement.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'feature',
                'verbose_name_plural': 'features',
                'ordering': ['group', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier. Safe to expose in APIs and URLs.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('reference_code', models.CharField(db_index=True, help_text='Human-quotable identifier used on the phone and in adverts.', max_length=20, unique=True)),
                ('short_description', models.CharField(blank=True, help_text='One or two lines, shown on the listing card.', max_length=300)),
                ('description', models.TextField(blank=True)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('studio', 'Studio'), ('house', 'House'), ('villa', 'Villa'), ('land', 'Land'), ('office', 'Office'), ('commercial', 'Commercial space'), ('industrial', 'Industrial space'), ('garage', 'Garage or parking')], db_index=True, max_length=20)),
                ('transaction_type', models.CharField(choices=[('sale', 'For sale'), ('rent', 'For rent')], db_index=True, max_length=10)),
                ('publication_status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('rented', 'Rented'), ('unavailable', 'Unavailable')], db_index=True, default='available', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('RON', 'Romanian leu'), ('USD', 'US dollar')], default='EUR', max_length=3)),
                ('rent_period', models.CharField(blank=True, choices=[('month', 'Per month'), ('week', 'Per week'), ('day', 'Per day')], help_text='Required for rentals, empty for sales.', max_length=10)),
                ('price_on_request', models.BooleanField(default=False, help_text='Hides the figure publicly; the value is still stored.')),
                ('rooms', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('usable_area', models.DecimalField(blank=True, decimal_places=2, help_text='Square metres.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_area', models.DecimalField(blank=True, decimal_places=2, help_text='Built or land area, in square metres.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('floor', models.SmallIntegerField(blank=True, help_text='0 is ground floor; negative is basement.', null=True)),
                ('total_floors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='locations.address')),
                ('agent', models.ForeignKey(help_text='The account responsible for this listing.', on_delete=django.db.models.deletion.PROTECT, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('cover_image', models.ForeignKey(blank=True, help_text='Denormalised so listing grids need no media query per row.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_properties', to='media.mediaasset')),
                ('features', models.ManyToManyField(blank=True, related_name='properties', to='properties.feature')),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['publication_status', 'availability_status', '-published_at'], name='prop_public_feed_idx'), models.Index(fields=['transaction_type', 'property_type', 'price'], name='prop_type_price_idx'), models.Index(fields=['agent', 'publication_status'], name='prop_agent_status_idx')],
            },
        ),
    ]
