# Generated by Django 5.2.17 on 2026-09-25 09:49

import apps.accounts.models.user
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier. Safe to expose in APIs and URLs.', unique=True)),
                ('phone_number', models.CharField(db_index=True, help_text='Stored in E.164 form. This is the login identifier.', max_length=20, unique=True, verbose_name='phone number')),
                ('first_name', models.CharField(blank=True, max_length=80, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=80, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], db_index=True, default='pending', max_length=16)),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Grants access to Django Admin, the internal CRUD fallback.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', apps.accounts.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier. Safe to expose in APIs and URLs.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.CharField(db_index=True, max_length=20)),
                ('purpose', models.CharField(choices=[('phone_confirmation', 'Phone confirmation'), ('password_reset', 'Password reset'), ('phone_change', 'Phone number change')], max_length=32)),
                ('code_hash', models.CharField(editable=False, max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Null while verifying a phone number that has no account yet.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'verification code',
                'verbose_name_plural': 'verification codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['destination', 'purpose', '-created_at'], name='accounts_ve_destina_c42a87_idx')],
            },
        ),
    ]
