# Generated by Django 5.2.17 on 2026-09-25 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier. Safe to expose in APIs and URLs.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('is_system', models.BooleanField(default=False, help_text='Generated by a workflow rather than typed by a person.')),
            ],
            options={
                'verbose_name': 'lead note',
                'verbose_name_plural': 'lead notes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier. Safe to expose in APIs and URLs.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('general', 'General contact'), ('property', 'Property enquiry'), ('development', 'Development enquiry'), ('viewing', 'Viewing request'), ('valuation', 'Valuation request')], db_index=True, default='general', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('closed', 'Closed'), ('spam', 'Spam')], db_index=True, default='new', max_length=16)),
                ('full_name', models.CharField(max_length=160)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField(blank=True)),
                ('contact_preference', models.CharField(choices=[('phone', 'Phone call'), ('sms', 'Text message'), ('email', 'Email'), ('any', 'Any')], default='any', max_length=10)),
                ('preferred_time', models.CharField(blank=True, help_text='Free text, e.g. weekday mornings.', max_length=120)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('source_path', models.CharField(blank=True, help_text='Page the form was submitted from.', max_length=255)),
                ('request_id', models.CharField(blank=True, help_text='Correlates with the server log for this request.', max_length=64)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('development', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='developments.development')),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
