# Generated by Django 5.2.17 on 2026-09-25 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier. Safe to expose in APIs and URLs.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('file_key', models.CharField(help_text='Opaque handle returned by the storage contract. Never a local path.', max_length=500, unique=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('document', 'Document')], default='image', max_length=16)),
                ('category', models.CharField(choices=[('gallery', 'Gallery image'), ('cover', 'Cover image'), ('layout', 'Apartment layout'), ('floor_plan', 'Building floor plan'), ('site_plan', 'Site plan'), ('document', 'Document'), ('certificate', 'Energy or legal certificate'), ('video_thumbnail', 'Video thumbnail')], db_index=True, default='gallery', max_length=20)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, help_text='Describes the image for screen readers and SEO.', max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_public', models.BooleanField(default=True, help_text='False keeps the file internal to the dashboard.')),
                ('object_id', models.PositiveBigIntegerField()),
                ('content_type_ref', models.ForeignKey(db_column='content_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'media asset',
                'verbose_name_plural': 'media assets',
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['content_type_ref', 'object_id', 'category', 'sort_order'], name='media_owner_category_idx')],
            },
        ),
    ]
