# Generated by Django 5.2.17 on 2026-09-25 09:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier. Safe to expose in APIs and URLs.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('areas', models.JSONField(blank=True, default=list, help_text='AccessArea values this role may reach.')),
                ('permissions', models.JSONField(blank=True, default=list, help_text='Dotted capability strings, e.g. properties.publish, leads.assign.')),
                ('is_system', models.BooleanField(default=False, help_text='System roles are seeded by the project and cannot be deleted.')),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='Lower wins when a single effective role must be chosen.')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'ordering': ['priority', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public identifier. Safe to expose in APIs and URLs.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'role assignment',
                'verbose_name_plural': 'role assignments',
                'ordering': ['role__priority'],
            },
        ),
    ]
